### ISSUE TITLE
Problem with go get

### ISSUE THREAD

**Issue by guitmz** [jpap/go-zydis#1]
Hello and thank you for this package! Just tried to get it in my machine and the following error occurred:

```
# code.jpap.org/go-zydis
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld:libzydis_linux_amd64.syso: file format not recognized; treating as linker script
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld:libzydis_linux_amd64.syso:1: syntax error
collect2: error: ld returned 1 exit status
```

at this point I want to ask if since the static libs (.syso) are already included, should I do anything extra? Zydis is installed in my machine.

Thanks!

**Comment by jpap** [comment]
> Hello and thank you for this package! 

My pleasure -- hope you find it useful!

> Just tried to get it in my machine and the following error occurred:

You must have Git LFS installed, as outlined in the `README.md` file.

Otherwise the `syso` files are just Git LFS pointers, for example,
```
version https://git-lfs.github.com/spec/v1
oid sha256:24c72fb67b79f2e2f0b67fa621a5224d99c2647d7e0b0a6e92419ef9a0b317f4
size 620992
```
and `ld` chokes as you have observed.

**Comment by guitmz** [comment]
Oh, my bad, you are correct, not sure how I missed that. Thanks again!

**Comment by Lexterl33t** [comment]
Hi, i have installed git-lfs but when i retry to install the lib the error is the same. :/

**Comment by jpap** [comment]
> Hi, i have installed git-lfs but when i retry to install the lib the error is the same. :/

Without any console output or logs, nobody can help you. ;-)  

I don't have time to provide free support for this project.  Perhaps you can get together with @guitmz, who solved the same issue with his git-lfs install.

**Comment by Lexterl33t** [comment]
Bro i have installed  git-lfs but the command do not work !

**Comment by Lexterl33t** [comment]
![image](https://user-images.githubusercontent.com/44911576/158039791-e2af5c0b-bc92-418f-9b8c-04c8bdf3a892.png)
![image](https://user-images.githubusercontent.com/44911576/158039803-673f5af9-dac1-4b11-8f6c-5b4d921a5697.png)
 can you help me please

**Comment by c0dycode** [comment]
I don't remember if this is the same issue I had previously.
When I tried it couple weeks ago, the actual issue that git lfs reported was that the "repo is out of bandwidth". Therefore it could not download the syso-files.

If this is the same issue, there are two workarounds:

1) Build zydis from source yourself and get the syso file(s) that way. If you go this way, make sure you use the v3-branch or you'll have to update the go-zydis code too.
2) Fork this repo, archive it and then download the repo as zip-file. You then should find the syso files inside of the archive.

**Comment by Lexterl33t** [comment]
I tested the two solutions above and it doesn't work, in fact I already had the .syso files because when I did a cat on them I had data such as the version, but in fact I have the impression that it's the file format that it doesn't recognise and I don't understand why, although it's a git lfs pointer and I do have git lfs installed And thanks for trying to help me.

**Comment by Lexterl33t** [comment]
![image](https://user-images.githubusercontent.com/44911576/158057612-6d7d6526-e978-4904-828d-cd3a111d8ac3.png)
in arch linux
