### ISSUE TITLE
git lfs - seems like you're running out of bandwidth

### ISSUE THREAD

**Issue by dzonerzy** [jpap/go-zydis#3]
This repository is over its data quota

**Comment by jpap** [comment]
I know... GitHub e-mails me about it all the time. ;-)

Over the past two weeks, there have been 281 clones by 115 uniques: that means the average package user is cloning 2.44 times on average.  It might be that some people are doing fresh Git LFS clones in their CI system...?

There's not much I can do here:
* This project is not funded, so I'm not willing to purchase GitHub data packs to extend the monthly quota.
* GitHub doesn't provide any LFS logs, and there is no way to contact the cloners to ask them to play nice(er).
* While Git LFS supports transport compression (only gzip) I'm unsure of whether GitHub supports it, or whether they count the full payload against quota even when gzip is deployed.  (I can't verify this by experimentation until the quota is refreshed.)  This might make the problem worse, and less effective use of $$ on data packs if that were an option.
* The Go module proxy doesn't support Git LFS so it doesn't cache any of the syso files, putting more pressure on the GitHub LFS server.
* Git LFS pulls down *all* syso files, even if only one is productive for a given build.  This amplifies pressure on the quota.

The only thing I can do is move the Git LFS server to another host, or move the project entirely to GitLab where quotas aren't as much of an issue.  That is something I may do in the future, but I lack the time to look into it in the short term.

One option available to you is to build the syso files yourself and vendor the package so you don't have to pull from GitHub.  I wish there was an easier option, my apologies.
