### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by ddkwork** [jpap/go-zydis#4]
How to build syso with.a file use clang or gcc on manjaro linux or windows11

**Comment by jpap** [comment]
Please take a look at `lib/Makefile` and modify the commands for your compiler accordingly.

**Comment by ddkwork** [comment]
> 请查看 `lib/Makefile` 及修改命令对于你的编译器。



> Please take a look at `lib/Makefile` and modify the commands for your compiler accordingly.

Sorry, when i change this

LD_WINDOWS_AMD64) -r -o ../libzydis_windows_amd64.syso --whole-archive out/windows_amd64/libZydis.a

To

gcc  -r -o ../libzydis_windows_amd64.syso --whole-archive out/windows_amd64/libZydis.a

and  build go demo,i found the syso has more and more function not bind and post some error  . Can you upload your lfs file1 or support build on linux? Thank you with my bad English.

Or witch cross builder i should install on manjaro linux?gcc?clang?

I was try to step this command:
Git lfs pull. But nothing happened.

Last i found build    .a File  is easy by cmake,
But a to syso is difficult to me, can you post a video for me lean?
