### ISSUE TITLE
build error using custom syso files?

### ISSUE THREAD

**Issue by ddkwork** [jpap/go-zydis#5]
![3285bc55fa70004fb8eed379f95293f1](https://user-images.githubusercontent.com/19886504/147077581-704381ce-6799-4840-bc5f-ddda81f4fc83.png)

hello,build sucess on mac 10.15 and run demo panic, last i copy all syso to win11 x64 and linux amd64,they are panic. can you test your demo?

or can you tell me how to build all .c .h file with cgo not use syso way?thank you.

**Comment by jpap** [comment]
No problems on linux/amd64, see below.

Your screenshot shows a build error, not a runtime panic.  Perhaps you are using syso files that you have built yourself?  Unfortunately you've not provided much detail to help understand what you're doing over there...

I'm very sorry, but I don't have the bandwidth to support you further: this GitHub Issue tracker is really meant for bugs, or feature requests.

```
$ uname -a
Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
$ go run cmd/demo.go 
Version: 3.1.0.0
007fffffff400000 55 push rbp
007fffffff400001 4889e5 mov rbp, rsp
007fffffff400004 4883e4e0 and rsp, 0xFFFFFFFFFFFFFFE0
007fffffff400008 4881eca0000000 sub rsp, 0xA0
007fffffff40000f c5f9efc0 vpxor xmm0, xmm0, xmm0
007fffffff400013 c5fd7f442460 vmovdqa [rsp+0x60], ymm0
007fffffff400019 c5fd7f442440 vmovdqa [rsp+0x40], ymm0
007fffffff40001f c5fd7f442420 vmovdqa [rsp+0x20], ymm0
007fffffff400025 c5fd7f0424 vmovdqa [rsp], ymm0
007fffffff40002a 4c8d0500000000 lea r8, [0x007FFFFFFF400031]
```

**Comment by ddkwork** [comment]
> 没有问题上linux/amd64，见下文。
> 
> 你的图显示了建立一个错误，不是一个运行时恐慌。 也许你们使用syso文件中，你建立自己？ 不幸的是你还没有提供太多的细节，以帮助了解你在做什么在那里...
> 
> 我很抱歉，但是我没有带宽，以支持你进一步：这个审查问题跟踪器是真正意味着错误，或功能要求。
> 
> ```
> $ uname -a
> Linux debian 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
> $ go run cmd/demo.go 
> Version: 3.1.0.0
> 007fffffff400000 55 push rbp
> 007fffffff400001 4889e5 mov rbp, rsp
> 007fffffff400004 4883e4e0 and rsp, 0xFFFFFFFFFFFFFFE0
> 007fffffff400008 4881eca0000000 sub rsp, 0xA0
> 007fffffff40000f c5f9efc0 vpxor xmm0, xmm0, xmm0
> 007fffffff400013 c5fd7f442460 vmovdqa [rsp+0x60], ymm0
> 007fffffff400019 c5fd7f442440 vmovdqa [rsp+0x40], ymm0
> 007fffffff40001f c5fd7f442420 vmovdqa [rsp+0x20], ymm0
> 007fffffff400025 c5fd7f0424 vmovdqa [rsp], ymm0
> 007fffffff40002a 4c8d0500000000 lea r8, [0x007FFFFFFF400031]
> ```

[](url)


https://user-images.githubusercontent.com/19886504/147090329-e72da5e5-ae10-4c9f-b2d8-4aec8491a10d.mp4

**Comment by c0dycode** [comment]
This most likely comes from @ddkwork building a new version from source (v4), which this binding unfortunately is incompatible with, at this time.

In v4 `ZydisDecoderDecodeBuffer` has been replaced by `ZydisDecoderDecodeFull` (along other changes), hence the "undefined symbol" error.

https://github.com/zyantific/zydis/blob/master/assets/porting-guide-v3-v4.md#zydisdecoder
